### ISSUE TITLE
Naming for setting mg_constraintsDictionary is not right

### ISSUE THREAD

**Issue by colasbd** [matteogobbi/UIView-MGConstraints#2]
```
- (void)setmg_constraintsDictionary:(NSMutableDictionary *)mg_constraintsDictionary
```

should be

```
- (void)setMg_constraintsDictionary:(NSMutableDictionary *)mg_constraintsDictionary
```

The category raises an exception in my project (`unknown message...`).

I've opened a PR.

**Comment by matteogobbi** [comment]
Merged

**Comment by colasbd** [comment]
@matteogobbi thanks

Can you update the pod?

**Comment by colasbd** [comment]
Your lib is nice and helped me to fix bug in auto layout.

**Comment by matteogobbi** [comment]
pod updated to version 1.2.

**Comment by colasbd** [comment]
Thanks @matteogobbi 
Sorry for pushing you.
